version: '2'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    command: >
      bash -c "curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
    user: jenkins
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
      - /var/lib/jenkins/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8030:8080"
      - "5000:5000"
      - "50000:50000"
